name: test
on:
  push:
    branches: [ Main ]
  pull_request:
    branches: [ Main ]

jobs:
  test:
    runs-on: ubuntu-22.04   # явно указываем версию, совпадающую с вашим базовым образом
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ngs-tools:latest .
